CREATE TABLE IF NOT EXISTS public."User" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS  public."UserRelationship" (
	"RelationshipId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"UserEmail" varchar NULL,
	"FriendEmail" varchar NULL,
	"IsFriend" bool NULL,
	"StatusUpdate" varchar NULL,
	CONSTRAINT "UserRelationship_pkey" PRIMARY KEY ("RelationshipId")
);

INSERT INTO public."User"
(id, email)
VALUES(158, 'minhtam@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(159, 'thaikhuong@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(160, 'truongthuan@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(161, 'minhson@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(162, 'quocthinh@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(163, 'thanhthien@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(164, 'thanhnam@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(165, 'tientam@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(166, 'hongthuan@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(167, 'truclinh@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(168, 'mylan@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(169, 'anhnguyet@gmail.com');
INSERT INTO public."User"
(id, email)
VALUES(170, 'mynhi@gmail.com');

INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(235, 'thaikhuong@gmail.com', 'minhson@gmail.com', true, '');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(236, 'minhson@gmail.com', 'truongthuan@gmail.com', true, '');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(237, 'minhson@gmail.com', 'thanhthien@gmail.com', true, '');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(238, 'minhson@gmail.com', 'mynhi@gmail.com', true, '');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(239, 'thanhthien@gmail.com', 'mynhi@gmail.com', true, '');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(240, 'thanhthien@gmail.com', 'truongthuan@gmail.com', true, '');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(241, 'anhnguyet@gmail.com', 'thanhthien@gmail.com', true, '');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(242, 'minhtam@gmail.com', 'thanhthien@gmail.com', true, '');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(243, 'truongthuan@gmail.com', 'quocthinh@gmail.com', false, 'SUBSCRIBE');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(244, 'truongthuan@gmail.com', 'minhtam@gmail.com', false, 'SUBSCRIBE');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(245, 'thaikhuong@gmail.com', 'minhtam@gmail.com', false, 'SUBSCRIBE');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(246, 'minhtam@gmail.com', 'mynhi@gmail.com', false, 'BLOCK');
INSERT INTO public."UserRelationship"
("RelationshipId", "UserEmail", "FriendEmail", "IsFriend", "StatusUpdate")
VALUES(247, 'mynhi@gmail.com', 'anhnguyet@gmail.com', false, 'BLOCK');

